blob:
  server:
    port: '6124'
taskmanager:
  memory:
    process:
      size: 1728Mb
  numberOfTaskSlots: 2
heartbeat:
  timeout: 5000
  interval: 1000
rest:
  flamegraph:
    enabled: true
jobmanager:
  rpc:
    address: jobmanager
  memory:
    process:
      size: 1600Mb
web:
  backpressure:
    refresh-interval: 10000
query:
  server:
    port: '6125'

state:
  # 2.0 使用 filesystem一直报错
#  backend: filesystem
  backend: hashmap
  savepoints:
    dir: file:///tmp/flink-savepoints-directory
  checkpoints:
    dir: file:///tmp/flink-checkpoints-directory
execution:
  checkpointing:
    savepoint-dir: file:///tmp/flink-checkpoints-directory
    dir: file:///tmp/flink-checkpoints-directory
